#!/bin/bash

# The name of the job:
#SBATCH --job-name="piperline.container_test"

# The project ID which this job should run under:
#SBATCH --account="pathogens"

# The partition in which to submit the job:
#SBATCH --partition="batch"

# Maximum number of tasks/CPU cores used by the job:
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1

# The total amount of memory in megabytes in the job:
#SBATCH --mem=20480

# Send yourself an email when the job:
# aborts abnormally (fails)
#SBATCH --mail-type=FAIL
# begins
#SBATCH --mail-type=BEGIN
# ends successfully
#SBATCH --mail-type=END

# Use this email address:
#SBATCH --mail-user=alexander.piper@agriculture.vic.gov.au

# The maximum running time of the job in days-hours:mins:sec
#SBATCH --time=7-0:0:00

# check that the script is launched with sbatch
if [ "x$SLURM_JOB_ID" == "x" ]; then
   echo "You need to submit your job to the queuing system with sbatch"
   exit 1
fi

module load shifter

# Update shifter image
# shifterimg pull docker:jackscanlan/piperline:0.0.2

# Run pipeline in shifter
shifter --image jackscanlan/piperline:0.0.2 --env=R_LIBS_USER=/usr/local/lib/R/site-library \
	Rscript ./R/basc_shifter.R

exit